apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetingservice-deploy
  namespace: greetingservice
  annotations:
    authproxy.stakater.com/target-port: "8888"
    authproxy.stakater.com/discovery-url: "http://keycloak:8180/auth/realms/greetingservice"
    authproxy.stakater.com/client-id: "greetingservice-client"
    authproxy.stakater.com/listen: ":8888"
    authproxy.stakater.com/encryption-key: "9984dd65-90f0-4122-901e-86d59a80"
    authproxy.stakater.com/enabled: "true"
    authproxy.stakater.com/source-service-name: "greetingservice"
    authproxy.stakater.com/resources: "uri=/*"
    authproxy.stakater.com/gatekeeper-image: "keycloak/keycloak-gatekeeper:latest"
    authproxy.stakater.com/enable-refresh-tokens: "true"
    authproxy.stakater.com/no-redirects: "true"
    authproxy.stakater.com/upstream-url: "http://localhost:8080"
spec:
  selector:
    matchLabels:
      app: greetingservice
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: greetingservice
    spec:
      #ToDo: InitContainer Prüfung ob notwendige Systeme (z.B. DB) verfügbar ist fehlt
      containers:
        - image: de.smartsquare/greetingservice
          imagePullPolicy: IfNotPresent
          name: greetingservice
          ports:
            - containerPort: 8080
      #ToDo: Resource-Limits und Requests auf CPU und RAM sollte noch definiert werden
      #ToDo: Readiness und Liveness-Probes fehlen
      restartPolicy: Always