apiVersion: v1
kind: Service
metadata:
  name: greetingservice
  namespace: greetingservice
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
  selector:
    app: greetingservice