apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  ports:
    - name: http
      port: 8180
      nodePort: 30081
      targetPort: keycloak-http
  selector:
    app: keycloak
  type: NodePort
