apiVersion: v1
kind: Service
metadata:
  name: greetingservice
  namespace: greetingservice
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 3000
    targetPort: 3000
  selector:
    app: greetingservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetingservice
  namespace: greetingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetingservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: greetingservice
    spec:
      containers:
      - name: service-gatekeeper
        image: keycloak/keycloak-gatekeeper:7.0.0
        imagePullPolicy: IfNotPresent
        args:
          - --config=/etc/config/gatekeeper-config.yaml
          - --enable-logging=true
          - --enable-json-logging=true
          - --verbose=true
        volumeMounts:
          - name: gatekeeper-config
            mountPath: /etc/config
      - image: de.smartsquare/greetingservice
        imagePullPolicy: IfNotPresent
        name: greetingservice
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
        - name: gatekeeper-config
          configMap:
            defaultMode: 420
            name: gatekeeper-config
            items:
              - key: gatekeeper-config.yaml
                path: gatekeeper-config.yaml