apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gatekeeper
  namespace: greetingservice
spec:
  selector:
    matchLabels:
      app: service-gatekeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: service-gatekeeper
      annotations:
        repository: https://github.com/keycloak/keycloak-gatekeeper
    spec:
      containers:
      - name: service-gatekeeper
        image: keycloak/keycloak-gatekeeper:7.0.0
        imagePullPolicy: IfNotPresent
        args:
        - --config=/etc/secrets/gatekeeper.yaml
        - --enable-logging=true
        - --enable-json-logging=true
        - --verbose=true
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
      volumes:
      - name: secrets
        secret:
          secretName: gatekeeper
