apiVersion: v1
kind: Service
metadata:
  name: reverseservice
  namespace: reverseservice
spec:
  ports:
    - name: http
      nodePort: 30090
      port: 8080
      targetPort: 8080
  selector:
    app: reverseservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseservice
  namespace: reverseservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: reverseservice
    spec:
      containers:
        - name: service-gatekeeper
          image: keycloak/keycloak-gatekeeper:7.0.0
          imagePullPolicy: IfNotPresent
          args:
            - --enable-logging=true
            - --enable-json-logging=true
            - --verbose=true
            - --listen=:3000
            - --discovery-url=http://keycloak.keycloak.svc:8180/auth/realms/greetingservice
            - --client-id=greetingservice-client
            - --client-secret=57803581-1d67-4851-9646-59b73018b6b4
            - --enable-forwarding=true
            - --forwarding-username=gsuser
            - --forwarding-password=gspass
        #            - --forwarding-domains=greetingservice.svc.cluster.local
        - image: de.smartsquare/reverseservice
          imagePullPolicy: IfNotPresent
          name: reverseservice
          ports:
            - containerPort: 8080
      restartPolicy: Always